Use nullptr instead of literal 0 in generated code (#30)
Fixes:
```
climatemodule.h:20:35: error: zero as null pointer constant [-Werror=zero-as-null-pointer-constant]
```